#! /bin/tcsh
#BSUB -J surfactant
#BSUB -o o.%J
#BSUB -e e.%J
#BSUB -n 16 
#BSUB -W 200:00 
#BSUB -R "select[oc || hc || qc] span[hosts=1]"
#BSUB -q santiso 
source /usr/local/apps/openmpi/intel2013_ompi.csh
grep -m 1 'model name' /proc/cpuinfo
which python

setenv nproc `echo $LSB_MCPU_HOSTS | cut -d " " -f2`

cp system_conf.data system_initial.data 

mpiexec -n $nproc src/lmp_henry2 -in system_initial.in > equil_initial.log

echo "#Surf Hist_0 Hist_1 Hist_2 Hist_3 Hist_4 Hist_5" > hist_data.dat
echo "Linear Analysis" > CSA_analysis.txt 

# loop ===============================
foreach xx (`seq 1 1 20`)

    # run LAMMPS
    mpiexec -n $nproc src/lmp_henry2 -in system_density.in > density_zdirection.log

    # copy old configuration as a backup
    cp density_zdirection.log ${xx}.log
    cp system_conf.data ${xx}_system_backup.conf
    cp terminal_polar.dat ${xx}_terminal_polar.dat
    cp surface.dat ${xx}_surface.dat
    cp nonpolar.dat ${xx}_nonpolar.dat
    cp histogram.dat ${xx}_histogram.dat 

    # run python to add molecules "python run_script dcd_file_name configuration_file_name number_of_surfactants output_file"
    python src/internal_src/Execute_Addition.py production.dcd system_conf.lt 10 system_info.txt

    if ($xx > $5) then
        python analysis/Hist_LinearRegression.py > CSA_analysis.txt 
end 

# ==================================
